volumes:
    mongo-data:
        external: true
services:
  fastapi-users:
    build:
      context: ./fastapi-users
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: mygamelist
      WAIT_HOSTS: mongo:27017
    ports:
      - 8000:8000
    volumes:
      - ./fastapi-users:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
    mongo:
      image: mongo:5
      volumes:
          - mongo-data:/data/db
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
